# Bellow the changes to default Rubocop behavior.

# See options at:
# https://github.com/bbatsov/rubocop/tree/master/config

# General

# Multi-line method chaining should be done with leading dots.
Layout/DotPosition:
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing

# Enabling
# --------

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size'
  Enabled: true

Style/StringMethods:
  Description: 'Checks if configured preferred methods are used over non-preferred.'
  Enabled: true

# Disabling
# ---------

# Modifying
# ---------

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
