---
language: ruby
dist: trusty
sudo: false
cache: bundler
script: "bundle exec rake test"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-3.81
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head

notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: ruby-head
    - rvm: rbx-3.81
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: jruby-head
  fast_finish: true
  include:
    - rvm: 1.9
      before_install:
        - "gem update --system -N"
        - "gem update bundler -N"
    - rvm: 2.5
      script: "bundle exec rake test && bundle exec codeclimate-test-reporter" # Run only for 2.4
bundler_args: --without code_quality
