---
language: ruby
sudo: false
script: "bundle exec rake test"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head

notifications:
  email: false
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: jruby-head
