---
language: ruby
dist: trusty
sudo: false
script: "bundle exec rake test && bundle exec codeclimate-test-reporter"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-3.81
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head

notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: ruby-head
    - rvm: rbx-3.81
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: jruby-head
bundler_args: --without development
